# Generated by Django 6.0.4 on 2026-05-04 16:49

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
def backfill_expires_at(apps, schema_editor):
    Contribution = apps.get_model('core', 'Contribution')
    for c in Contribution.objects.filter(status='pending', expires_at__isnull=True):
        c.expires_at = c.created_at + datetime.timedelta(days=7)
        c.save(update_fields=['expires_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_contribution_status_alter_profile_role_dispute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Send goods before this time; otherwise the contribution may expire.', null=True),
        ),
        migrations.RunPython(backfill_expires_at, migrations.RunPython.noop),
        migrations.AddField(
            model_name='request',
            name='delivery_location',
            field=models.TextField(blank=True, help_text='Where contributors should send goods (station, building, department, contact window, etc.).'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('verified', 'Verified'), ('expired', 'Expired (not delivered in time)')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_contributor', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(help_text='Usually the user who created the request.', on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_receiver', to=settings.AUTH_USER_MODEL)),
                ('resource_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.request')),
            ],
            options={
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('resource_request', 'contributor'), name='unique_conversation_per_request_contributor'),
        ),
    ]
