# Generated by Django 6.0.4 on 2026-05-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contribution_expires_at_request_delivery_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='delivery_country',
            field=models.CharField(choices=[('UA', 'Ukraine'), ('OTHER', 'Other (free text only — no carrier map)')], default='UA', max_length=16),
        ),
        migrations.AddField(
            model_name='request',
            name='delivery_kind',
            field=models.CharField(choices=[('manual', 'Manual description'), ('nova_poshta', 'Nova Poshta (parcel locker / branch)'), ('ukrposhta', 'Ukrposhta (post office)')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='request',
            name='dropoff_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='dropoff_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='np_city_ref',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='request',
            name='np_label',
            field=models.TextField(blank=True, help_text='Snapshot of selected NP warehouse for display.'),
        ),
        migrations.AddField(
            model_name='request',
            name='np_warehouse_ref',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='request',
            name='up_label',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='request',
            name='up_office_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='request',
            name='up_postcode',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
