# Generated by Django 6.0.4 on 2026-05-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_request_dropoff_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passport_scan',
            field=models.FileField(blank=True, null=True, upload_to='verifications/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_dropoff_point',
            field=models.TextField(blank=True, help_text='Your preferred post office / branch / pickup point (free text).'),
        ),
        migrations.AddField(
            model_name='profile',
            name='reserve_plus_pdf',
            field=models.FileField(blank=True, null=True, upload_to='verifications/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('none', 'Not submitted'), ('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='none', max_length=16),
        ),
    ]
