# Generated by Django 6.0.4 on 2026-05-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_moderation_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_dropoff_kind',
            field=models.CharField(blank=True, choices=[('manual', 'Manual description'), ('nova_poshta', 'Nova Poshta (parcel locker / branch)'), ('ukrposhta', 'Ukrposhta (post office)')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_np_city_ref',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_np_label',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_np_warehouse_ref',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_up_label',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_up_office_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_up_postcode',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
