# Generated by Django 6.0.4 on 2026-05-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_profile_preferred_dropoff_refs'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='closed_reason',
            field=models.TextField(blank=True),
        ),
    ]
