# Generated by Django 6.0.4 on 2026-05-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_request_close_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('proposed', 'Awaiting request owner'), ('revision_requested', 'Changes requested by owner'), ('declined', 'Declined by request owner'), ('withdrawn', 'Withdrawn by contributor'), ('pending', 'Accepted — send within deadline'), ('approved', 'Approved (staff)'), ('rejected', 'Rejected (staff)'), ('verified', 'Verified'), ('expired', 'Expired (not delivered in time)')], default='proposed', max_length=24),
        ),
    ]
