# Generated by Django 6.0.4 on 2026-05-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_contribution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='restricted_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='restricted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
