# Generated by Django 6.0.4 on 2026-05-05 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_profile_restricted_reason_profile_restricted_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationreport',
            name='action_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moderationreport',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_reports_actioned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationreport',
            name='action_duration_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moderationreport',
            name='action_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='moderationreport',
            name='action_taken',
            field=models.CharField(choices=[('none', 'No action'), ('unrestrict', 'Unrestrict'), ('restrict_temp', 'Temporary restrict'), ('ban_permanent', 'Permanent ban')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='banned_reason',
            field=models.TextField(blank=True),
        ),
    ]
