# Generated by Django 6.0.4 on 2026-05-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_request_staff_warning_request_staff_warning_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_np_city_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='request',
            name='np_city_label',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
