"""
Django settings for diploma_project project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Ukraine carriers (optional — without keys, UA UI falls back to manual text + map pin).
NOVA_POSHTA_API_KEY = os.environ.get("NOVA_POSHTA_API_KEY", "")
# When True: always use offline Nova Poshta demo data (even if NOVA_POSHTA_API_KEY is set).
NOVA_POSHTA_OFFLINE_DEMO = os.environ.get("NOVA_POSHTA_OFFLINE_DEMO", "").strip().lower() in (
    "1",
    "true",
    "yes",
)
# Offline demo: 3 cities + branches if API key empty, or when NOVA_POSHTA_OFFLINE_DEMO is enabled.
_np_key_stripped = (NOVA_POSHTA_API_KEY or "").strip()
NOVA_POSHTA_USE_MOCK_DATA = (not _np_key_stripped) or NOVA_POSHTA_OFFLINE_DEMO
UKRPOSHTA_BEARER_TOKEN = os.environ.get("UKRPOSHTA_BEARER_TOKEN", "")
# Example when your Ukrposhta contract exposes GET search-by-postcode:
# UKRPOSHTA_POSTCODE_SEARCH_URL = "https://example/api/offices?postcode={postcode}"
UKRPOSHTA_POSTCODE_SEARCH_URL = os.environ.get("UKRPOSHTA_POSTCODE_SEARCH_URL", "")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-)48f(kxg!=%7290ds2^q2=!4r64q@!nk(ym9wmrzxk+t6_rthi",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "1").strip().lower() in ("1", "true", "yes")

ALLOWED_HOSTS = [h.strip() for h in (os.environ.get("ALLOWED_HOSTS", "") or "").split(",") if h.strip()]
if DEBUG and not ALLOWED_HOSTS:
    # Dev defaults (also needed for Django test client host "testserver").
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "testserver"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # API + auth protocols
    'rest_framework',
    'drf_spectacular',
    'oauth2_provider',
    'core.apps.CoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'core.middleware.RateLimitMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.SecurityHeadersMiddleware',
]

# Rate limiting rules (fixed window).
# For production multi-instance deployments, set RATE_LIMIT_CACHE_ALIAS to a shared cache (e.g. Redis).
RATE_LIMIT_RULES = {
    # Anti-bruteforce (paths include language prefix from i18n_patterns, e.g. /en/login/)
    "POST /en/login/": {"window_seconds": 60, "max_requests": 10, "key_prefix": "login", "include_username": True},
    "POST /uk/login/": {"window_seconds": 60, "max_requests": 10, "key_prefix": "login", "include_username": True},
    "POST /login/": {"window_seconds": 60, "max_requests": 10, "key_prefix": "login", "include_username": True},
    # Token endpoints
    "POST /o/token/": {"window_seconds": 60, "max_requests": 20, "key_prefix": "oauth_token"},
    "POST /api/auth/jwt/token/": {"window_seconds": 60, "max_requests": 20, "key_prefix": "jwt_token"},
    # Anti-spam (i18n-prefixed create URL)
    "POST /en/create/": {"window_seconds": 60, "max_requests": 6, "key_prefix": "create_request"},
    "POST /uk/create/": {"window_seconds": 60, "max_requests": 6, "key_prefix": "create_request"},
    "POST /create/": {"window_seconds": 60, "max_requests": 6, "key_prefix": "create_request"},
    "POST /requests/": {"window_seconds": 60, "max_requests": 30, "key_prefix": "requests_list"},
    "POST /requests/*/report/": {"window_seconds": 60, "max_requests": 8, "key_prefix": "report_request"},
}

# OAuth2 provider settings (authorization server)
OAUTH2_PROVIDER = {
    "ACCESS_TOKEN_EXPIRE_SECONDS": 60 * 30,  # 30 min
    "REFRESH_TOKEN_EXPIRE_SECONDS": 60 * 60 * 24 * 7,  # 7 days
    "ROTATE_REFRESH_TOKEN": True,
    # For demo/testing: keep client secrets usable in /o/token/ (admin UI may show hashed secrets otherwise).
    # In production you can enable hashing, but then you must store the *plain* secret securely at creation time.
    "HASH_CLIENT_SECRETS": False,
    # For diploma demo: do not require PKCE on authorization code.
    # (If you want stricter security later, enable PKCE and generate code_challenge in the client.)
    "PKCE_REQUIRED": False,
    "SCOPES": {
        "read": "Read access",
        "write": "Write access",
        "staff": "Staff operations",
    },
}

ROOT_URLCONF = 'diploma_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.staff_portal',
            ],
        },
    },
]

WSGI_APPLICATION = 'diploma_project.wsgi.application'


# DRF / OpenAPI
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # OAuth2 Bearer tokens (authorization server / integrations)
        "oauth2_provider.contrib.rest_framework.OAuth2Authentication",
        # JWT for API access (alternative)
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        # Keep session auth for browsable API + local admin/dev
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Diploma Fulfillment API",
    "DESCRIPTION": "REST API for the coordination system.",
    "VERSION": "1.0.0",
    # Avoid schema surprises from implicit auth; we will list schemes explicitly later.
}

# SimpleJWT
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
if DATABASE_URL:
    DATABASES["default"] = dj_database_url.parse(DATABASE_URL, conn_max_age=600)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'uk'

LANGUAGES = [
    ("uk", _("Ukrainian")),
    ("en", _("English")),
    ("de", _("German")),
]

LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

LANGUAGE_COOKIE_NAME = "django_language"

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    }
}

# Render / HTTPS proxy
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in (os.environ.get("CSRF_TRUSTED_ORIGINS", "") or "").split(",")
    if o.strip()
]

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "3600"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = False

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
LOGIN_URL = '/login/'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'